### ISSUE TITLE
`docker-compose build` results in

### ISSUE THREAD

**Issue by zdavatz** [nilsmango/7III_Location_API#1]
1. `docker-compose build`
2. results in
```
└─$ docker-compose build
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 417, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.11/http/client.py", line 1294, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1340, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1289, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1048, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 986, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 800, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 417, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.11/http/client.py", line 1294, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1340, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1289, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1048, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 986, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
                        ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
           ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
             ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
```

**Comment by zdavatz** [comment]
Get one step further with: `sudo docker-compose build`

**Comment by zdavatz** [comment]
1. I can start the app with `sudo docker-compose up app db`
2. but it then crashes with
```
app_1      | *** Signal 4: Backtracing from 0x55fb2b6e01b2... done ***
app_1      |
app_1      | *** Program crashed: Illegal instruction at 0x000055fb2b6e01b2 ***
app_1      |
app_1      | Thread 4 "NIO-ELT-0-#2" crashed:
app_1      |
app_1      | 0               0x000055fb2b6e01b2 _assertionFailure(_:_:file:line:flags:) + 354 in App
app_1      | 1 [ra]          0x000055fb2b74719c swift_errorInMain + 619 in App
app_1      | 2 [ra] [system] 0x000055fb2aaaeb81 specialized thunk for @escaping @convention(thin) @async () -> () + 32 in App at /build/<compiler-generated>
app_1      | 3 [async]       0x000055fb2ba37ee0 completeTaskAndRelease(swift::AsyncContext*, swift::SwiftError*) in App
app_1      |
app_1      |
app_1      | Registers:
app_1      |
app_1      | rax 0x0000000200000003  8589934595
app_1      | rdx 0x000055fb2c75ad7d  46 61 74 61 6c 20 65 72 72 6f 72 00 6c 6f 77 65  Fatal error·lowe
app_1      | rcx 0xfffffffe00000000  18446744065119617024
app_1      | rbx 0x0000000000000003  3
app_1      | rsi 0x00007f178c436188  03 00 00 00 00 00 00 00 58 01 00 00 00 00 00 80  ········X·······
app_1      | rdi 0x00007f178b3fbe98  01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ················
app_1      | rbp 0x00007f178b3fb280  00 b3 3f 8b 17 7f 00 00 9c 71 74 2b fb 55 00 00  ·³?······qt+ûU··
app_1      | rsp 0x00007f178b3fb1e0  f0 b1 3f 8b 17 7f 00 00 3b 2f 82 2b fb 55 00 00  ð±?·····;/·+ûU··
app_1      |  r8 0x00007f17944008c0  c8 00 00 00 c8 00 00 00 c8 00 00 00 c8 00 00 00  È···È···È···È···
app_1      |  r9 0x0000000000000180  384
app_1      | r10 0x0000000000000038  56
app_1      | r11 0x00007f178b3fd640  40 d6 3f 8b 17 7f 00 00 50 d1 47 91 17 7f 00 00  @Ö?·····PÑG·····
app_1      | r12 0x0000000000000000  0
app_1      | r13 0x000000000000013d  317
app_1      | r14 0x00007f178c436180  70 ba 54 2e fb 55 00 00 03 00 00 00 00 00 00 00  pºT.ûU··········
app_1      | r15 0x000000000000000b  11
app_1      | rip 0x000055fb2b6e01b2  0f 0b 48 83 ec 08 48 8d 05 a1 c1 06 01 48 8d 3d  ··H·ì·H··¡Á··H·=
app_1      |
app_1      | rflags 0x0000000000010246  ZF PF
app_1      |
app_1      | cs 0x0033  fs 0x0000  gs 0x0000
app_1      |
app_1      |
app_1      | Images:
app_1      |
app_1      | 0x000055fb2a42d000–0x000055fb2c637c68 <no build ID>                            App                  /app/App
app_1      | 0x00007f179461b000–0x00007f17947d7341 c289da5071a3399de893d2af81d6a30c62646e1e libc.so.6            /usr/lib/x86_64-linux-gnu/libc.so.6
app_1      | 0x00007f1794846000–0x00007f179485f815 e3a44e0da9c6e835d293ed8fd2882b4c4a87130c libgcc_s.so.1        /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
app_1      | 0x00007f1794866000–0x00007f179490863d ffdb577fa78a283f51714728e64d35d30bac41a9 libjemalloc.so.2     /usr/lib/x86_64-linux-gnu/libjemalloc.so.2
app_1      | 0x00007f1794b40000–0x00007f1794b52c21 30840b79ac329ecbf1dec0bb60180eed256d319f libz.so.1.2.11       /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
app_1      | 0x00007f1794b5c000–0x00007f1794d06fd1 e37fe1a879783838de78cbc8c80621fa685d58a2 libstdc++.so.6.0.30  /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30
app_1      | 0x00007f1794d88000–0x00007f1794e118d5 a88ef0199bd5e742ebd0c359edf5cb2be0ec08b5 libm.so.6            /usr/lib/x86_64-linux-gnu/libm.so.6
app_1      | 0x00007f1794e73000–0x00007f1794e9e315 15921ea631d9f36502d20459c43e5c85b7d6ab76 ld-linux-x86-64.so.2 /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
app_1      |
app_1      | Backtrace took 4.84s
app_1      |
7iii_location_api_app_1 exited with code 132
```

**Comment by zdavatz** [comment]
starting it again, I get:
```
app_1      | [ DEBUG ] Servicing connection waitlist item with id 2 [database-id: psql] (AsyncKit/EventLoopConnectionPool.swift:286)
app_1      | [ INFO ] [Migrator] Finished prepare [database-id: psql, migration: App.CreateRunMemberPivot] (FluentKit/Migrator.swift:207)
app_1      | [ DEBUG ] query create _fluent_migrations input=[[batch: 1, created_at: 2024-03-08 20:39:28 +0000, id: 36D9DC8D-BD25-4491-A5A1-3F92D5C5BE37, name: "App.CreateRunMemberPivot", updated_at: 2024-03-08 20:39:28 +0000]] [database-id: psql] (FluentKit/QueryBuilder.swift:293)
app_1      | [ DEBUG ] INSERT INTO "_fluent_migrations" ("id", "name", "batch", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id" [[36D9DC8D-BD25-4491-A5A1-3F92D5C5BE37, "App.CreateRunMemberPivot", 1, 2024-03-08 20:39:28 +0000, 2024-03-08 20:39:28 +0000]] [database-id: psql] (PostgresKit/PostgresDatabase+SQL.swift:44)
app_1      | [ NOTICE ] Server starting on http://0.0.0.0:8080 (Vapor/HTTPServer.swift:297)
```

**Comment by zdavatz** [comment]
![PHOTO-2024-03-08-21-52-28](https://github.com/nilsmango/7III_Location_API/assets/4953/4e1057dd-4351-48e0-ae92-4294ddcd528d)
